	  PROGRAM GRADE_AVERAGER
	  IMPLICIT NONE

	  CHARACTER(len=20) :: NAME
	  REAL :: GRADE=0, TOTAL=0, AVERAGE
	  INTEGER :: N, I

	  PRINT *, 'WELCOME TO THE GRADE AVERAGER'
	  PRINT *, 'PROGRAM 2 BY GROUP 1'
	  PRINT *, 'BY NICK PEZZA AND BRANDON ARNOLD'

	  PRINT *, 'ENTER STUDENTS NAME'
	  READ (*,*) NAME

	  PRINT *, 'ENTER THE NUMBER OF GRADES FOR ', NAME 
	  READ (*,*) N

	  DO I=1, N
	     PRINT *, 'ENTER GRADE', I
	     READ (*,*) GRADE
	     TOTAL= GRADE + TOTAL
	  END DO
	  
	  AVERAGE = TOTAL/N

	  PRINT *, NAME, 'GRADE IS ', AVERAGE

	  END PROGRAM GRADE_AVERAGER